FROM openjdk:11
EXPOSE 8084
ADD ./target/AppointmentBookingService-1.0-SNAPSHOT-jar-with-dependencies.jar AppointmentBookingService-1.0-SNAPSHOT-jar-with-dependencies.jar
ENTRYPOINT ["java","-jar", "AppointmentBookingService-1.0-SNAPSHOT-jar-with-dependencies.jar"]
